header: |
  /***************************************************************
   *  Copyright notice
   *
   *  (c) 2017 Andre Wuttig <wuttig@portrino.de>, portrino GmbH
   *
   *  All rights reserved
   *
   *  This script is part of the TYPO3 project. The TYPO3 project is
   *  free software; you can redistribute it and/or modify
   *  it under the terms of the GNU General Public License as published by
   *  the Free Software Foundation; either version 3 of the License, or
   *  (at your option) any later version.
   *
   *  The GNU General Public License can be found at
   *  http://www.gnu.org/copyleft/gpl.html.
   *
   *  This script is distributed in the hope that it will be useful,
   *  but WITHOUT ANY WARRANTY; without even the implied warranty of
   *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   *  GNU General Public License for more details.
   *
   *  This copyright notice MUST APPEAR in all copies of the script!
   ***************************************************************/
namespaces:
  entity: Portrino\PxSemantic\SchemaOrg
  enum: Portrino\PxSemantic\SchemaOrg\Enum
annotationGenerators:
  - ApiPlatform\SchemaGenerator\AnnotationGenerator\PhpDocAnnotationGenerator
author: "Andre Wuttig<wuttig@portrino.de>"
debug: true
types:
  Action:
    properties:
      actionStatus: ~
      target: ~
  ActionStatusType:
  AdministrativeArea:
  AggregateRating:
    properties:
      ratingCount: ~
  Airline:
    properties:
      iataCode: ~
  Answer:
    properties:
        downvoteCount: ~
        parentItem: ~
        upvoteCount: ~
  Article:
    properties:
      articleBody: ~
      articleSection: ~
      pageEnd: { range: "Text" }
      pageStart: { range: "Text" }
      pagination: ~
      wordCount: ~
  CollectionPage:
    properties:
      lastReviewed: ~
  Comment:
    properties:
      downvoteCount: ~
      parentItem: ~
      upvoteCount: ~
  ContactPoint:
    properties:
      areaServed: { range: "Text" }
      availableLanguage: { range: "Language" }
      contactType: ~
      email: ~
      faxNumber: ~
      telephone: ~
  Corporation:
    properties:
      tickerSymbol: ~
  Country:
  CreativeWork:
    properties:
      about: ~
      author: { range: "Person" }
      aggregateRating: ~
      comment: ~
      commentCount: ~
      dateCreated: { range: "DateTime" }
      datePublished: ~
      dateModified: { range: "DateTime" }
      headline: ~
      publisher: { range: "Organization" }
      text: ~
  Date:
  DateTime:
  Duration:
    properties:
      name: ~
  EducationalOrganization:
    properties:
      alumni: ~
  Energy:
  EngineSpecification:
    properties:
      fuelType: ~
  EntryPoint:
    properties:
      contentType: ~
  Event:
    properties:
      about: ~
      actor: ~
      aggregateRating: ~
      attendee: ~
      startDate: ~
      endDate: ~
      composer: ~
      director: ~
      contributor: ~
  GeoCoordinates:
  GeoShape:
  ImageObject:
    properties:
      url: ~
      height: { range: "Integer" }
      width: { range: "Integer" }
  Intangible:
  Integer:
  ItemList:
    properties:
      itemListElement: { range: "Text" }
  ItemPage:
    properties:
      lastReviewed: ~
  Language:
  LocalBusiness:
    properties:
      currenciesAccepted: ~
      openingHours: ~
  LocationFeatureSpecification:
  Mass:
  MediaObject:
    properties:
      height: { range: "Integer" }
      width: { range: "Integer" }
      duration: ~
  Number:
  NutritionInformation:
    properties:
      servingSize: ~
      calories: ~
      fatContent: ~
  Offer:
    properties:
      eligibleDuration: ~
      eligibleQuantity: ~
      priceCurrency: ~
      price: { range: "Text" }
  OpeningHoursSpecification:
    properties:
      closes: ~
      opens: ~
      validFrom: ~
      validThrough: ~
  Organization:
    properties:
      address: { range: "PostalAddress" }
      aggregateRating: { range: "AggregateRating" }
      alumni: ~
      areaServed: { range: "Text" }
      award: ~
      brand: { range: "Organization" }
      contactPoint: { range: "ContactPoint" }
      contactPoints: ~
      department: ~
      dissolutionDate: ~
      duns: ~
      email: ~
      employee: ~
      faxNumber: ~
      founder: ~
      foundingDate: ~
      foundingLocation: ~
      globalLocationNumber: ~
      hasPOS: ~
      isicV4: ~
      legalName: ~
      location: { range: "Place" }
      logo: { range: "ImageObject" }
      member: { range: "Organization" }
      memberOf: { range: "Organization" }
      naics: ~
      numberOfEmployees: ~
      parentOrganization: ~
      review: ~
      subOrganization: ~
      taxID: ~
      telephone: ~
      vatID: ~
  Person:
    properties:
      additionalName: ~
      address: { range: "PostalAddress" }
      affiliation: ~
      alumniOf: { range: "Organization" }
      award: ~
      birthDate: ~
      birthPlace: ~
      brand: { range: "Organization" }
      children: ~
      colleague: { range: "Person" }
      contactPoint: ~
      deathDate: ~
      duns: ~
      email: ~
      familyName: ~
      faxNumber: ~
      follows: ~
      gender: ~
      givenName: ~
      globalLocationNumber: ~
      height: ~
      homeLocation: { range: "ContactPoint" }
      honorificPrefix: ~
      honorificSuffix: ~
      isicV4: ~
      jobTitle: ~
      knows: ~
      memberOf: ~
      naics: ~
      nationality: ~
      parent: ~
      relatedTo: ~
      sibling: ~
      sponsor: { range: "Organization" }
      taxID: ~
      telephone: ~
      vatID: ~
      weight: ~
      workLocation: { range: "ContactPoint" }
      worksFor: ~
  Place:
    properties:
      aggregateRating: ~
      address: { range: "PostalAddress" }
      branchCode: ~
      globalLocationNumber: ~
  PostalAddress:
    properties:
      addressCountry: { range: "Text" }
      addressLocality: ~
      addressRegion: ~
      postOfficeBoxNumber: ~
      postalCode: ~
      streetAddress: ~
  Product:
    properties:
      additionalProperty: ~
      aggregateRating: ~
      brand: ~
      category: ~
      color: ~
      depth: ~
      height: ~
      logo: ~
      manufacturer: ~
      material: ~
      model: ~
      mpn: ~
      productID: ~
      productionDate: ~
      purchaseDate: ~
      releaseDate: ~
      weight: ~
      width: { range: "QuantitativeValue" }
      offers: ~
  PropertyValue:
  QAPage:
    properties:
      lastReviewed: ~
  Quantity:
  QualitativeValue:
    properties:
      equal: ~
      greater: ~
      greaterOrEqual: ~
      lesser: ~
      lesserOrEqual: ~
      nonEqual: ~
  QuantitativeValue:
    properties:
      maxValue: ~
      minValue: ~
      unitCode: { range: "Text" }
      unitText: ~
      value: { range: "Text" }
  Question:
    properties:
      acceptedAnswer: ~
      answerCount: ~
      downvoteCount: ~
      suggestedAnswer: ~
      upvoteCount: ~
  Rating:
    properties:
      bestRating: { range: "Number" }
      ratingCount: { range: "Number" }
      ratingValue: { range: "Number" }
      worstRating: { range: "Number" }
  Recipe:
    properties:
      prepTime: { range: "Text" }
      cookTime: { range: "Text" }
      totalTime: { range: "Text" }
      recipeYield: ~
      nutrition: ~
      recipeIngredient: { range: "Text" }
      recipeInstructions: { range: "Text" }
  Review:
    properties:
      itemReviewed: ~
      reviewBody: ~
      reviewRating: ~
  School:
    properties:
      address: ~
  SearchResultsPage:
    properties:
      lastReviewed: ~
  SportsOrganization:
    properties:
      sport: { range: "Text" }
  SportsTeam:
    properties:
        athlete: ~
        coach: ~
  SteeringPositionValue:
    properties:
      additionalProperty: ~
  StructuredValue:
  TechArticle:
    properties:
      dependencies: ~
      proficiencyLevel: ~
  Text:
  Thing:
    parent: false
    properties:
      additionalType: ~
      alternateName: ~
      description: ~
      image: { range: "ImageObject" }
      mainEntityOfPage: { range: "URL" }
      name: ~
      potentialAction: ~
      sameAs: ~
      url: ~
  URL:
  Vehicle:
    properties:
      cargoVolume: ~
      dateVehicleFirstRegistered: ~
      driveWheelConfiguration: {range: "Text" }
      fuelConsumption: ~
      fuelEfficiency: ~
      fuelType: ~
      knownVehicleDamages: ~
      numberOfAirbags: ~
      numberOfAxles: ~
      numberOfDoors: ~
      numberOfForwardGears: ~
      numberOfPreviousOwners: ~
      productionDate: ~
      purchaseDate: ~
      steeringPosition: ~
      vehicleConfiguration: ~
      vehicleEngine: ~
      vehicleIdentificationNumber: ~
      vehicleInteriorColor: ~
      vehicleInteriorType: ~
      vehicleModelDate: ~
      vehicleSeatingCapacity: ~
      vehicleSpecialUsage: ~
      vehicleTransmission: ~
  WebPage:
    properties:
      breadcrumb: { range: "Text" }
      lastReviewed: ~
      primaryImageOfPage: ~
      relatedLink: ~
  WebSite:
    properties:
      about: ~
