<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "px_semantic"
 *
 * Auto generated by Extension Builder 2014-01-20
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Portrino Semantic Web Library',
    'description' => 'Structured Data Rendering for TYPO3',
    'category' => 'fe',
    'author' => 'Andre Wuttig',
    'author_email' => 'wuttig@portrino.de',
    'author_company' => 'portrino GmbH',
    'state' => 'beta',
    'uploadfolder' => '0',
    'clearCacheOnLoad' => 0,
    'version' => '2.5.1',
    'constraints' => [
        'depends' => [
            'typo3' => '6.2.0-8.7.99',
        ],
        'conflicts' => [
        ],
        'suggests' => [
        ],
    ],
];